export const SET_PROFILE = "SET_PROFILE";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_POSITIONS = "SET_POSITIONS";
export const SET_PROCEDURE_DETAIL_STATUS = "SET_PROCEDURE_DETAIL_STATUS"
export const SET_PROCEDURE_STATUS = "SET_PROCEDURE_STATUS"
